kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - image: registry.web.boeing.com/rohit.thomas/dockerimages/jms_kafka:{{.Values.imageVersion}}
        name: web-server
        ports:
          - containerPort: 8171
            protocol: TCP
