apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-curd-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage