kind: Service
apiVersion: v1
metadata:
  name: web-server-service
  labels:
    app: web-server
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web-server
  type: ClusterIP
